## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("Vacation_Search/WeatherPy_vacation.csv")
vacation_df.head()

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,0,Vaini,TO,80.76,light rain,-21.2000,-175.2000,Keleti Beach Resort
1,2,Saint-Philippe,RE,81.95,light rain,-21.3585,55.7679,"Chambres d'hôte ""La Trinité"""
2,16,Matara,LK,82.02,overcast clouds,5.9485,80.5353,Amaloh Boutique Resort
3,19,Rikitea,PF,76.39,broken clouds,-23.1203,-134.9692,People ThankYou
4,21,Kapaa,US,75.18,clear sky,22.0752,-159.3190,Sheraton Kauai Coconut Beach Resort

In [3]:
# 2. Using the template add the city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>

"""

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]

In [4]:
# 4a. Add a marker layer for each city to the map.
locations = vacation_df[["Lat", "Lng"]]
max_temp = vacation_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
aus_df = vacation_df[vacation_df["Country"] == "AU"]
aus_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
15,61,Geraldton,AU,88.21,clear sky,-28.7667,114.6000,Broadwater Mariner Resort
16,62,Carnarvon,AU,89.67,clear sky,-24.8667,113.6333,Hospitality Carnarvon
17,66,Esperance,AU,82.53,clear sky,-33.8667,121.9000,Hospitality Esperance
22,80,Busselton,AU,84.15,broken clouds,-33.6500,115.3333,Observatory Guest House
27,101,Cairns,AU,85.95,light rain,-16.9167,145.7667,Mantra Trilogy Cairns
36,139,Townsville,AU,83.28,few clouds,-19.2500,146.8000,Rydges Southbank Townsville
43,170,Alyangula,AU,89.47,thunderstorm,-13.8483,136.4192,Groote Eylandt Lodge
49,198,Mildura,AU,82.36,clear sky,-34.2000,142.1500,Mercure Hotel Mildura
92,383,Yulara,AU,85.84,clear sky,-25.2406,130.9889,Desert Gardens Hotel - Ayers Rock Resort
98,400,Port Augusta,AU,80.74,few clouds,-32.5000,137.7667,Majestic Oasis Apartments
115,467,Narrabri,AU,77.47,broken clouds,-30.3167,149.7833,Crossroads Hotel
116,468,Kyabram,AU,79.56,clear sky,-36.3167,145.0500,Kyabram Motor Inn
120,480,Yeppoon,AU,78.58,few clouds,-23.1333,150.7333,Villa Mar Colina
121,481,Hervey Bay,AU,77.11,light rain,-25.2986,152.8535,Shelly Bay Resort
155,621,Charters Towers,AU,87.82,broken clouds,-20.1000,146.2667,Cattleman's Rest Motor Inn
164,652,Bowen,AU,83.82,scattered clouds,-20.0167,148.2333,Castle Motor Lodge Motel

In [10]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities.
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.
start_city = "Charters Towers"
end_city = "Charters Towers"
city1 = "Bowen"
city2 = "Cairns"
city3 = "Townsville"

vacation_start = vacation_df.loc[vacation_df["City"] == start_city]
vacation_end = vacation_df.loc[vacation_df["City"] == end_city]
vacation_stop1 = vacation_df.loc[vacation_df["City"] == city1]
vacation_stop2 = vacation_df.loc[vacation_df["City"] == city2] 
vacation_stop3 = vacation_df.loc[vacation_df["City"] == city3]

In [11]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()[0]
end = vacation_end[["Lat", "Lng"]].to_numpy()[0]
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()[0]
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()[0]
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()[0]

In [12]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
fig = gmaps.figure()
travel_route = gmaps.directions_layer(start, end, waypoints=[stop1,stop2,stop3], travel_mode="DRIVING" or "BICYCLING" or "WALKING")
fig.add_layer(travel_route)
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

,City_ID,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,621,Charters Towers,AU,87.82,broken clouds,-20.1000,146.2667,Cattleman's Rest Motor Inn
1,652,Bowen,AU,83.82,scattered clouds,-20.0167,148.2333,Castle Motor Lodge Motel
2,101,Cairns,AU,85.95,light rain,-16.9167,145.7667,Mantra Trilogy Cairns
3,139,Townsville,AU,83.28,few clouds,-19.2500,146.8000,Rydges Southbank Townsville

In [14]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Weather Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp}</dd>
</dl>
"""

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [15]:
# 11a. Add a marker layer for each city to the map.
fig = gmaps.figure()
markers = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(markers)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))